"""
Leak-free win-probability models for the paper-1 revision (Table I, the
feature-set design, greedy-search value functions, the augmented model).

Protocol (identical optimizer to retrain_frozen_stats.train_wp_model: AdamW
lr 5e-4, wd 5e-3, cosine T_max 100, batch 4096, dropout 0.3, <=200 epochs,
patience 25), with two changes from the submission:
  * early stopping and seed selection use the VALIDATION split (core.is_val),
    never the test set;
  * training-row features use out-of-fold statistics (core: oof{k}); val,
    test and post-snapshot rows use the deploy statistics (train games only).
Every spec is trained with 3 seeds (42, 123, 777). The "selected" checkpoint
is the seed with the lowest validation loss; tables report the 3-seed mean.

Metrics per seed, on the paper test set (38,981) and on post-snapshot
no-drift games (NODRIFT, 291,837; overfit2026.gold):
  acc      accuracy over both team orders (the submission's Table I convention)
  ll, acc_sym, slope   log-loss / accuracy / calibration slope of the
           team-order-symmetrized prediction (slope = logistic regression of
           the outcome on logit(p); 1.0 = calibrated, <1 = overconfident)

Usage: python3 paper1_revision/train_wp.py <spec>[,<spec>...] [--gpu 0]
       python3 paper1_revision/train_wp.py --list
"""
import os
import sys
import json
import time
import argparse

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.dirname(HERE))
from paper1_revision import core

import numpy as np

SEEDS = (42, 123, 777)
SWEPT = ["map_type", "role_counts", "hero_wr", "team_avg_wr", "hero_map_wr",
         "map_delta", "pairwise_counters", "pairwise_synergies", "counter_detail",
         "synergy_detail"]


def enriched_groups():
    from experiment_synthetic_augmentation import ENRICHED_GROUPS
    return list(ENRICHED_GROUPS)


def specs():
    E = enriched_groups()
    S = {
        "naive": dict(groups=[], arch=[256, 128]),
        "herostrength": dict(groups=["hero_wr", "team_avg_wr"], arch=[256, 128]),
        "enriched": dict(groups=E, arch=[256, 128]),
        "enriched_leak": dict(groups=E, arch=[256, 128], feats="train_leak"),
        "enriched_512": dict(groups=E, arch=[512, 256, 128]),
        "relational": dict(groups=[g for g in E if g not in
                                   ("meta_strength", "comp_wr", "team_avg_wr")],
                           arch=[256, 128]),
        "absolute": dict(groups=[g for g in E if g not in
                                 ("counter_detail", "pairwise_counters",
                                  "pairwise_synergies")], arch=[256, 128]),
    }
    for wr in (0, 5, 10, 50):
        S[f"aug_wr{wr}_512"] = dict(groups=E, arch=[512, 256, 128], synth=wr)
    for mask in sweep_design():
        name = "sw_" + "".join("1" if b else "0" for b in mask)
        S[name] = dict(groups=[g for g, b in zip(SWEPT, mask) if b], arch=[256, 128],
                       seeds=(42,))
    return S


def sweep_design():
    """2^(10-3) resolution-V fractional factorial over the 10 swept groups
    (128 runs). Base factors = groups 0..6; groups 7, 8, 9 are generated by
    fixed 5-letter words found by exhaustive search (every word of the defining
    relation has length >= 5, so main effects and two-factor interactions are
    unaliased with each other)."""
    gens = _res5_generators()
    runs = []
    for r in range(128):
        base = [(r >> i) & 1 for i in range(7)]
        sgn = [1 - 2 * b for b in base]                # 0 -> +1, 1 -> -1
        extra = []
        for w in gens:
            p = 1
            for i in range(7):
                if (w >> i) & 1:
                    p *= sgn[i]
            extra.append(p)
        levels = sgn + extra
        runs.append(tuple(v < 0 for v in levels))      # -1 = group ON
    return runs


def _res5_generators():
    import itertools
    words = [w for w in range(1, 128) if bin(w).count("1") >= 4]
    for combo in itertools.combinations(words, 3):
        ok = True
        # defining relation: each generator word * its new factor, and products
        for k in range(1, 8):
            base = 0
            n_new = 0
            for j in range(3):
                if (k >> j) & 1:
                    base ^= combo[j]
                    n_new += 1
            if bin(base).count("1") + n_new < 5:
                ok = False
                break
        if ok:
            return combo
    raise RuntimeError("no resolution-V design")


def _tensors(cols, feats_name, device):
    import torch
    Xf, Xs, y, rid, tier = core.load_features(feats_name)
    X = np.concatenate([Xf[:, cols], Xs[:, cols]])
    Y = np.concatenate([y, 1 - y])
    return torch.tensor(X, device=device), torch.tensor(Y, device=device)


def synth_rows(wr, cols):
    """Synthetic records for role compositions absent from the own-corpus
    deploy composition table (experiment_synthetic_augmentation v2 generator:
    pairwise-adjusted labels, volume 100 per unseen composition per tier)."""
    import random
    path = os.path.join(core.FEAT_DIR, f"synth_wr{wr}.npz")
    if not os.path.exists(path):
        from experiment_synthetic_augmentation import generate_synthetic_data_v2
        random.seed(42)
        np.random.seed(42)
        sp = core.split_games()
        real = [{"team0_heroes": list(g[3]), "team1_heroes": list(g[4])} for g in sp["train"]]
        comp_raw = json.load(open(core.comp_path("deploy")))
        syn, _ = generate_synthetic_data_v2(real, comp_raw, core.load_stats("deploy"),
                                            unseen_wr=float(wr), unseen_volume=100)
        # features: each synthetic row takes the statistics of a round-robin
        # fold, like a real training row (labels come from deploy statistics)
        Xf = np.zeros((len(syn), 357), np.float32)
        Xs = np.zeros_like(Xf)
        idx = np.arange(len(syn)) % core.N_FOLDS
        for k in range(core.N_FOLDS):
            ii = np.where(idx == k)[0]
            rows = [(syn[i]["team0_heroes"], syn[i]["team1_heroes"], syn[i]["game_map"],
                     syn[i]["skill_tier"]) for i in ii]
            a, b = core.featurize(rows, core.load_stats(f"oof{k}"))
            Xf[ii], Xs[ii] = a, b
        y = np.array([1.0 if r["winner"] == 0 else 0.0 for r in syn], np.float32)
        np.savez(path, Xf=Xf, Xs=Xs, y=y)
        print(f"synthetic wr={wr}: {len(syn):,} records, mean label {y.mean():.3f}", flush=True)
    z = np.load(path)
    return (np.concatenate([z["Xf"][:, cols], z["Xs"][:, cols]]),
            np.concatenate([z["y"], 1 - z["y"]]))


def fit_slope(p, y):
    from overfit2026.gold import fit_logistic
    p = np.clip(p, 1e-6, 1 - 1e-6)
    c, _ = fit_logistic(np.log(p / (1 - p))[:, None], y)
    return float(c[1])


def evaluate(model, cols, feats_name, device):
    import torch
    Xf, Xs, y, rid, tier = core.load_features(feats_name)
    out = []
    with torch.no_grad():
        for X in (Xf, Xs):
            ps = []
            for i in range(0, len(X), 65536):
                ps.append(model(torch.tensor(X[i:i + 65536][:, cols], device=device)
                                ).float().view(-1).cpu().numpy())
            out.append(np.concatenate(ps))
    pf, ps_ = out
    acc_both = float(0.5 * (np.mean((pf > .5) == (y > .5)) + np.mean((ps_ > .5) == (y < .5))))
    p = np.clip(0.5 * (pf + 1 - ps_), 1e-6, 1 - 1e-6)
    return {"n": int(len(y)), "acc": acc_both,
            "acc_sym": float(np.mean((p > .5) == (y > .5))),
            "ll": float(-np.mean(y * np.log(p) + (1 - y) * np.log(1 - p))),
            "slope": fit_slope(p, y),
            "mean_abs_logit": float(np.abs(np.log(p / (1 - p))).mean())}


def train_one(name, spec, seed, device, tensors):
    import torch
    import torch.nn as nn
    from sweep_enriched_wp import WinProbEnrichedModel
    tX, tY, vX, vY = tensors
    torch.manual_seed(seed)
    np.random.seed(seed)
    model = WinProbEnrichedModel(tX.shape[1], spec["arch"], dropout=0.3).to(device)
    crit = nn.BCELoss()
    opt = torch.optim.AdamW(model.parameters(), lr=spec.get("lr", 5e-4), weight_decay=5e-3)
    sch = torch.optim.lr_scheduler.CosineAnnealingLR(opt, T_max=100, eta_min=1e-5)
    best, best_state, pat, hist = float("inf"), None, 0, []
    n = len(tX)
    for ep in range(200):
        model.train()
        pm = torch.randperm(n, device=device)
        for i in range(0, n, 4096):
            idx = pm[i:i + 4096]
            loss = crit(model(tX[idx]).view(-1), tY[idx])
            opt.zero_grad()
            loss.backward()
            opt.step()
        sch.step()
        model.eval()
        with torch.no_grad():
            vp = model(vX).view(-1)
            vl = crit(vp, vY).item()
            va = ((vp > 0.5).float() == vY).float().mean().item()
        hist.append((ep + 1, round(vl, 6), round(va, 5)))
        if vl < best:
            best, pat = vl, 0
            best_state = {k: v.detach().cpu().clone() for k, v in model.state_dict().items()}
        else:
            pat += 1
            if pat >= 25:
                break
    model.load_state_dict(best_state)
    model.eval()
    return model, best, hist


def run_spec(name, spec, device):
    import torch
    out_json = os.path.join(core.MODEL_DIR, f"{name}.json")
    if os.path.exists(out_json):
        print(f"skip {name} (done)")
        return
    cols = core.group_cols(spec["groups"])
    t0 = time.time()
    tX, tY = _tensors(cols, spec.get("feats", "train_oof"), device)
    if spec.get("synth") is not None:
        sX, sY = synth_rows(spec["synth"], cols)
        tX = torch.cat([tX, torch.tensor(sX, device=device)])
        tY = torch.cat([tY, torch.tensor(sY, device=device)])
    vX, vY = _tensors(cols, "val", device)
    res = {"name": name, "spec": spec, "input_dim": int(len(cols)),
           "n_train_rows": int(len(tX)), "n_val_rows": int(len(vX)), "seeds": {}}
    for seed in spec.get("seeds", SEEDS):
        model, vl, hist = train_one(name, spec, seed, device, (tX, tY, vX, vY))
        torch.save(model.state_dict(), os.path.join(core.MODEL_DIR, f"{name}_s{seed}.pt"))
        r = {"val_loss": vl, "epochs": len(hist), "history": hist}
        for fs in ("test", "NODRIFT"):
            r[fs] = evaluate(model, cols, fs, device)
        res["seeds"][str(seed)] = r
        print(f"  {name} s{seed}: ep={len(hist)} val_ll={vl:.5f} "
              f"test acc={r['test']['acc']:.4f} slope={r['test']['slope']:.3f} | "
              f"NODRIFT acc={r['NODRIFT']['acc']:.4f} slope={r['NODRIFT']['slope']:.3f} "
              f"({time.time() - t0:.0f}s)", flush=True)
    sel = min(res["seeds"], key=lambda s: res["seeds"][s]["val_loss"])
    res["selected_seed"] = int(sel)
    for fs in ("test", "NODRIFT"):
        res[f"{fs}_mean"] = {k: float(np.mean([res["seeds"][s][fs][k] for s in res["seeds"]]))
                             for k in ("acc", "acc_sym", "ll", "slope")}
        res[f"{fs}_sd"] = {k: float(np.std([res["seeds"][s][fs][k] for s in res["seeds"]], ddof=1))
                           if len(res["seeds"]) > 1 else 0.0
                           for k in ("acc", "acc_sym", "ll", "slope")}
    json.dump(res, open(out_json, "w"), indent=1)
    del tX, tY, vX, vY
    torch.cuda.empty_cache()


def load(name, seed=None, device="cpu"):
    """-> (model, cols) for the selected (or given) seed."""
    import torch
    from sweep_enriched_wp import WinProbEnrichedModel
    meta = json.load(open(os.path.join(core.MODEL_DIR, f"{name}.json")))
    seed = seed or meta["selected_seed"]
    cols = core.group_cols(meta["spec"]["groups"])
    m = WinProbEnrichedModel(len(cols), meta["spec"]["arch"], dropout=0.3)
    m.load_state_dict(torch.load(os.path.join(core.MODEL_DIR, f"{name}_s{seed}.pt"),
                                 map_location="cpu", weights_only=True))
    m.eval()
    return m.to(device), cols


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("names", nargs="?", default="")
    ap.add_argument("--list", action="store_true")
    a = ap.parse_args()
    S = specs()
    if a.list:
        for k, v in S.items():
            print(k, len(core.group_cols(v["groups"])), v.get("arch"))
        return
    import torch
    dev = torch.device("cuda")
    names = []
    for tok in a.names.split(","):
        names += [n for n in S if n == tok or (tok.endswith("*") and n.startswith(tok[:-1]))]
    for n in names:
        run_spec(n, S[n], dev)


if __name__ == "__main__":
    main()
