using System.Text.Json;
using System.Text.Json.Serialization;
using HotsFever.DraftEngine.Encoding;
using HotsFever.DraftEngine.Models;
using Xunit;
using Xunit.Abstractions;

namespace HotsFever.DraftEngine.Tests;

/// <summary>
/// The parity oracle (model layer): validates the C# engine against reference
/// vectors produced by onnxruntime-web â€” the runtime production uses.
///   Layer 1: C# re-encodes each case's draft state and it must match the web
///            input tensors byte-for-byte (encoding parity).
///   Layer 2: C# ORT outputs must match the web ORT outputs within margin, and
///            the top pick (argmax over available heroes) must agree.
///
/// The golden file is generated by tools/oracle (`npm run gen`). If it is
/// missing these tests are skipped, so the suite stays green pre-generation.
/// </summary>
public class OracleParityTests
{
    private readonly ITestOutputHelper _out;
    public OracleParityTests(ITestOutputHelper o) => _out = o;

    // Within-margin tolerances (per the M1 plan: web-wasm vs .NET-native are not bit-identical).
    private const double LogitAtol = 5e-3, LogitRtol = 5e-3;
    private const double ScalarAtol = 3e-3;
    private const double EncodingAtol = 1e-6; // Layer 1 is essentially exact (only step/15 is non-0/1)

    private sealed class Golden { [JsonPropertyName("cases")] public List<Case> Cases { get; set; } = new(); }
    private sealed class Case
    {
        public CaseMeta Meta { get; set; } = new();
        public double[] PolicyState { get; set; } = Array.Empty<double>();
        public double[] Mask { get; set; } = Array.Empty<double>();
        public double[] GdState { get; set; } = Array.Empty<double>();
        public double[] WpInput { get; set; } = Array.Empty<double>();
        public Outputs Outputs { get; set; } = new();
    }
    private sealed class CaseMeta
    {
        public string[] Team0Picks { get; set; } = Array.Empty<string>();
        public string[] Team1Picks { get; set; } = Array.Empty<string>();
        public string[] Bans { get; set; } = Array.Empty<string>();
        public string Map { get; set; } = "";
        public string Tier { get; set; } = "mid";
        public int Step { get; set; }
        public bool IsPick { get; set; }
        public int OurTeam { get; set; }
    }
    private sealed class Outputs
    {
        public double[] PolicyLogits { get; set; } = Array.Empty<double>();
        public double Value { get; set; }
        public double[] HeroLogits { get; set; } = Array.Empty<double>();
        public double WinProbability { get; set; }
    }

    private static Golden? LoadGolden()
    {
        var path = TestPaths.OracleGolden();
        if (path == null) return null;
        return JsonSerializer.Deserialize<Golden>(File.ReadAllText(path),
            new JsonSerializerOptions { PropertyNameCaseInsensitive = true });
    }

    private static AiDraftState ToState(CaseMeta m) => new()
    {
        Team0Picks = m.Team0Picks, Team1Picks = m.Team1Picks, Bans = m.Bans,
        Map = m.Map, Tier = m.Tier, Step = m.Step, IsPick = m.IsPick, OurTeam = m.OurTeam,
    };

    private static bool Close(double a, double b, double atol, double rtol)
        => Math.Abs(a - b) <= atol + rtol * Math.Abs(b);

    [Fact]
    public void Layer1_Encoding_MatchesWebTensors()
    {
        var g = LoadGolden();
        if (g == null) { _out.WriteLine("SKIP: oracle-golden.json not generated (run tools/oracle: npm run gen)"); return; }

        double maxDiff = 0;
        foreach (var c in g!.Cases)
        {
            var s = ToState(c.Meta);
            var policy = StateEncoder.EncodeState(s);
            var gd = StateEncoder.EncodeStateForGd(s);
            var mask = StateEncoder.BuildValidMask(c.Meta.Team0Picks.Concat(c.Meta.Team1Picks).Concat(c.Meta.Bans));

            for (int i = 0; i < policy.Length; i++) maxDiff = Math.Max(maxDiff, Math.Abs(policy[i] - c.PolicyState[i]));
            for (int i = 0; i < gd.Length; i++) Assert.True(Math.Abs(gd[i] - c.GdState[i]) <= EncodingAtol);
            for (int i = 0; i < mask.Length; i++) Assert.True(Math.Abs(mask[i] - c.Mask[i]) <= EncodingAtol);
            for (int i = 0; i < policy.Length; i++) Assert.True(Math.Abs(policy[i] - c.PolicyState[i]) <= EncodingAtol,
                $"policy[{i}] {policy[i]} vs web {c.PolicyState[i]}");
        }
        _out.WriteLine($"Layer 1: {g.Cases.Count} cases, max encoding diff = {maxDiff:E3}");
    }

    [Fact]
    public void Layer2_Policy_MatchesWebWithinMargin()
    {
        var g = LoadGolden();
        if (g == null) { _out.WriteLine("SKIP: oracle-golden.json not generated"); return; }
        using var sessions = OnnxSessions.FromDirectory(TestPaths.ModelsDir());

        double maxLogit = 0, maxVal = 0; int argmaxMismatch = 0;
        foreach (var c in g!.Cases)
        {
            var r = sessions.RunPolicy(ToFloat(c.PolicyState), ToFloat(c.Mask));
            for (int i = 0; i < r.PolicyLogits.Length; i++)
            {
                maxLogit = Math.Max(maxLogit, Math.Abs(r.PolicyLogits[i] - c.Outputs.PolicyLogits[i]));
                Assert.True(Close(r.PolicyLogits[i], c.Outputs.PolicyLogits[i], LogitAtol, LogitRtol),
                    $"policyLogits[{i}] C#={r.PolicyLogits[i]} web={c.Outputs.PolicyLogits[i]}");
            }
            maxVal = Math.Max(maxVal, Math.Abs(r.Value - c.Outputs.Value));
            Assert.True(Close(r.Value, c.Outputs.Value, ScalarAtol, 0));
            if (Argmax(r.PolicyLogits, c.Mask) != Argmax(c.Outputs.PolicyLogits, c.Mask)) argmaxMismatch++;
        }
        _out.WriteLine($"Layer 2 policy: max logit diff={maxLogit:E3}, max value diff={maxVal:E3}, argmax mismatches={argmaxMismatch}/{g.Cases.Count}");
        Assert.Equal(0, argmaxMismatch);
    }

    [Fact]
    public void Layer2_GenericDraft_MatchesWebWithinMargin()
    {
        var g = LoadGolden();
        if (g == null) { _out.WriteLine("SKIP: oracle-golden.json not generated"); return; }
        using var sessions = OnnxSessions.FromDirectory(TestPaths.ModelsDir());

        double maxLogit = 0; int argmaxMismatch = 0;
        foreach (var c in g!.Cases)
        {
            var logits = sessions.RunGenericDraft(ToFloat(c.GdState), ToFloat(c.Mask));
            for (int i = 0; i < logits.Length; i++)
            {
                maxLogit = Math.Max(maxLogit, Math.Abs(logits[i] - c.Outputs.HeroLogits[i]));
                Assert.True(Close(logits[i], c.Outputs.HeroLogits[i], LogitAtol, LogitRtol));
            }
            if (Argmax(logits, c.Mask) != Argmax(c.Outputs.HeroLogits, c.Mask)) argmaxMismatch++;
        }
        _out.WriteLine($"Layer 2 GD: max logit diff={maxLogit:E3}, argmax mismatches={argmaxMismatch}/{g.Cases.Count}");
        Assert.Equal(0, argmaxMismatch);
    }

    [Fact]
    public void Layer2_WinProbability_MatchesWebWithinMargin()
    {
        var g = LoadGolden();
        if (g == null) { _out.WriteLine("SKIP: oracle-golden.json not generated"); return; }
        using var sessions = OnnxSessions.FromDirectory(TestPaths.ModelsDir());

        double maxDiff = 0;
        foreach (var c in g!.Cases)
        {
            var p = sessions.RunWinProbability(ToFloat(c.WpInput));
            maxDiff = Math.Max(maxDiff, Math.Abs(p - c.Outputs.WinProbability));
            Assert.True(Close(p, c.Outputs.WinProbability, ScalarAtol, 0),
                $"winProbability C#={p} web={c.Outputs.WinProbability}");
        }
        _out.WriteLine($"Layer 2 WP: max diff={maxDiff:E3} over {g.Cases.Count} cases");
    }

    private static float[] ToFloat(double[] d)
    {
        var f = new float[d.Length];
        for (int i = 0; i < d.Length; i++) f[i] = (float)d[i];
        return f;
    }

    private static int Argmax(IReadOnlyList<double> vals, double[] mask)
    {
        int best = -1; double bestV = double.NegativeInfinity;
        for (int i = 0; i < vals.Count; i++)
            if (mask[i] > 0 && vals[i] > bestV) { bestV = vals[i]; best = i; }
        return best;
    }
    private static int Argmax(IReadOnlyList<float> vals, double[] mask)
    {
        int best = -1; double bestV = double.NegativeInfinity;
        for (int i = 0; i < vals.Count; i++)
            if (mask[i] > 0 && vals[i] > bestV) { bestV = vals[i]; best = i; }
        return best;
    }
}

